<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>QuickPrintStudio</AssemblyName>
    <RootNamespace>QuickPrintStudio.Addon</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuickPrintStudio.Core\QuickPrintStudio.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>